/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.studentmanagementsystem.view;

import edu.ijse.studentmanagementsystem.controller.ControllerFactory;
import edu.ijse.studentmanagementsystem.controller.custo.AttendenceController;
import edu.ijse.studentmanagementsystem.controller.custo.RegistrationController;
import edu.ijse.studentmanagementsystem.controller.custo.SubjectController;
import edu.ijse.studentmanagementsystem.dto.AttendenceDTO;
import edu.ijse.studentmanagementsystem.dto.RegistrationDTO;
import edu.ijse.studentmanagementsystem.dto.SubjectDTO;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Krishanthi
 */
public class Attendence extends javax.swing.JPanel {

    private AttendenceController ctrlattendence;
    private RegistrationController ctrlReg;
    private SubjectController ctrlSubject;
    private DefaultTableModel dtmAttendence;

    /**
     * Creates new form Attendence
     */
    public Attendence() {
        initComponents();
        ctrlReg = (RegistrationController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.REGISTRATION);
        ctrlSubject = (SubjectController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.SUBJECT);
        ctrlattendence = (AttendenceController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.ATTENDENCE);
        loadRegisterIds();
        loadSubjectIds();
        dtmAttendence = (DefaultTableModel) tblAttendence.getModel();
        loadData();
        handleEvents();
    }

    private void loadSubjectIds() {
        try {
            ArrayList<SubjectDTO> SubjectIdList = ctrlSubject.getAll();
            for (SubjectDTO subjectId : SubjectIdList) {
                cmbSubjectId.addItem(subjectId.getName());
            }
        } catch (Exception e) {
        }
    }

    private void loadRegisterIds() {
        try {
            ArrayList<RegistrationDTO> RegisterIdList = ctrlReg.getAll();
            for (RegistrationDTO registerId : RegisterIdList) {
                cmbRegisterId.addItem(registerId.getRid());
            }
        } catch (Exception e) {
        }
    }
    /* private void searchAttendence() {

     try {
     AttendenceDTO attendenceDTO = ctrlattendence.search(txtSearch.getText());

     if (attendenceDTO != null) {

     //enableTxt();
     txtAttendenceId.setText(attendenceDTO.getAttend_id());
     //cmbRegisterId.set
     //cmb
     txtDate.setText(attendenceDTO.getDate());
     txtTime.setText(""+attendenceDTO.getTime());
     if (attendenceDTO.getPresent_mark().equalsIgnoreCase("Present")) {
     rbnPresent.setSelected(true);
     }else{
                
     rbnAbsent.setSelected(true);
     }
     btnUpdate.setEnabled(true);
     btnDelete.setEnabled(true);
     } else {

     JOptionPane.showMessageDialog(this, "null");
     }
     } catch (Exception ex) {
     Logger.getLogger(Attendence.class.getName()).log(Level.SEVERE, null, ex);
     }
     }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgRegistration = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblAttendenceId = new javax.swing.JLabel();
        txtAttendenceId = new javax.swing.JTextField();
        lblRegisterId = new javax.swing.JLabel();
        lblSubjectId = new javax.swing.JLabel();
        cmbSubjectId = new javax.swing.JComboBox();
        cmbRegisterId = new javax.swing.JComboBox();
        lblDate = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        lblTime = new javax.swing.JLabel();
        txtTime = new javax.swing.JTextField();
        lblPresentMark = new javax.swing.JLabel();
        rbnPresent = new javax.swing.JRadioButton();
        rbnAbsent = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnAdd1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAttendence = new javax.swing.JTable();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 153));
        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ATTENDENCE");
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 60));

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jLabel2.setText("Attendence");

        lblAttendenceId.setText("ATTENDENCE ID");

        lblRegisterId.setText("REGISTER ID");

        lblSubjectId.setText("SUBJECT ID");

        cmbSubjectId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSubjectIdActionPerformed(evt);
            }
        });

        lblDate.setText("DATE");

        lblTime.setText("TIME");

        lblPresentMark.setText("PRESENT MARK");

        btgRegistration.add(rbnPresent);
        rbnPresent.setText("PRESENT");

        btgRegistration.add(rbnAbsent);
        rbnAbsent.setText("ABSENT");

        btnAdd1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/studentmanagementsystem/view/linecons_e00f(0)_32.png"))); // NOI18N
        btnAdd1.setText("ADD");
        btnAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addComponent(jSeparator3)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtAttendenceId, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbSubjectId, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbRegisterId, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDate, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTime, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAttendenceId, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRegisterId, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSubjectId, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTime, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPresentMark, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(rbnPresent)
                                .addGap(18, 18, 18)
                                .addComponent(rbnAbsent))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 120, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAdd1)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(lblAttendenceId, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAttendenceId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRegisterId, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbRegisterId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSubjectId, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbSubjectId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTime, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPresentMark, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbnPresent)
                    .addComponent(rbnAbsent))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 290, 470));

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });

        tblAttendence.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ATTENDENCE", "REGISTER ID", "SUBJECT NAME", "DATE", "TIME", "PRESENT MARK"
            }
        ));
        jScrollPane1.setViewportView(tblAttendence);

        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/studentmanagementsystem/view/Material Icons_e884(0)_32.png"))); // NOI18N
        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/studentmanagementsystem/view/linecons_e006(0)_32.png"))); // NOI18N
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/studentmanagementsystem/view/linecons_e009(0)_32.png"))); // NOI18N
        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator4)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDelete)
                        .addGap(66, 66, 66))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(15, Short.MAX_VALUE))))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 760, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        String attendenceId = dtmAttendence.getValueAt(tblAttendence.getSelectedRow(), 0).toString();
        try {
            boolean deleted = ctrlattendence.delete(attendenceId);
            if (deleted) {
                //clearFields();
                //setEnable(false);
                loadData();
                tblAttendence.clearSelection();
                //btnNewSubject.requestFocusInWindow();
                JOptionPane.showMessageDialog(this, "DELETE Success");
            } else {

              JOptionPane.showMessageDialog(this,
                    "Attendence deletion has been failed, Please try again.",
                    "Delete Error",
                    JOptionPane.ERROR_MESSAGE
            );   

            }
        } catch (Exception ex) {

           
            Logger.getLogger(Attendence.class.getName()).log(Level.SEVERE, null, ex);
        }
        /*String attendenceId = dtmAttendence.getValueAt(tblAttendence.getSelectedRow(), 0).toString();
         try {
         boolean deleted = ctrlattendence.delete(attendenceId);
         if (deleted) {
         //clearFields();
         //setEnable(false);
         loadData();
         tblAttendence.clearSelection();
         //btnNewSubject.requestFocusInWindow();
         } else {

         JOptionPane.showMessageDialog(this,"Delete Error");
         }
         } catch (Exception ex) {

         JOptionPane.showMessageDialog(this,
         "Attendence deletion has been failed, Please try again.",
         "Delete Error",
         JOptionPane.ERROR_MESSAGE
         );
         Logger.getLogger(Attendence.class.getName()).log(Level.SEVERE, null, ex);
         }*/
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void cmbSubjectIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSubjectIdActionPerformed

    }//GEN-LAST:event_cmbSubjectIdActionPerformed

    private void btnAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd1ActionPerformed
        String attendeceId = txtAttendenceId.getText();
        String rid = cmbRegisterId.getSelectedItem().toString();
        String sub_id = cmbSubjectId.getSelectedItem().toString();
        String date = txtDate.getText();
        Double time = (Double.parseDouble(txtTime.getText()));

        String present_mark = "";

        if (rbnPresent.isSelected()) {
            present_mark = "present";
        }

        if (rbnAbsent.isSelected()) {
            present_mark = "absent";

        }

        AttendenceDTO attendenceDTO = new AttendenceDTO(attendeceId, rid, sub_id, date, time, present_mark);

        try {

            boolean add = ctrlattendence.add(attendenceDTO);
            if (add) {

                JOptionPane.showMessageDialog(this, "Success");
                loadData();
            } else {

                JOptionPane.showMessageDialog(this, "something went wrong");
            }

        } catch (Exception ex) {
            Logger.getLogger(Attendence.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAdd1ActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try {
            String attendeceId = txtAttendenceId.getText();
            String rid = cmbRegisterId.getSelectedItem().toString();
            String sub_id = cmbSubjectId.getSelectedItem().toString();
            String date = txtDate.getText();
            Double time = (Double.parseDouble(txtTime.getText()));

            String present_mark = "";

            if (rbnPresent.isSelected()) {
                present_mark = "present";
            }

            if (rbnAbsent.isSelected()) {
                present_mark = "absent";

            }

            AttendenceDTO attendenceDTO = new AttendenceDTO(attendeceId, rid, sub_id, date, time, present_mark);

            boolean isUpdate = ctrlattendence.update(attendenceDTO);
            if (isUpdate) {
                JOptionPane.showMessageDialog(Attendence.this, "Update Success...");
                loadData();
                //clearFields();
            } else {
                JOptionPane.showMessageDialog(Attendence.this, "Update Fail");
            }
        } catch (Exception ex) {
            Logger.getLogger(Attendence.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        String aid = txtSearch.getText();
        try {
            AttendenceDTO attendence = ctrlattendence.search(aid);
            if (attendence == null) {

            } else {
             
                Object[] rowData = {
                    attendence.getAttend_id(),
                    attendence.getRid(),
                    attendence.getSub_id(),
                    attendence.getDate(),
                    attendence.getTime(),
                    attendence.getPresent_mark()

                };

                dtmAttendence.setRowCount(0);
                dtmAttendence.addRow(rowData);
            }
        } catch (Exception ex) {
            Logger.getLogger(Attendence.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_txtSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgRegistration;
    private javax.swing.JButton btnAdd1;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox cmbRegisterId;
    private javax.swing.JComboBox cmbSubjectId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblAttendenceId;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblPresentMark;
    private javax.swing.JLabel lblRegisterId;
    private javax.swing.JLabel lblSubjectId;
    private javax.swing.JLabel lblTime;
    private javax.swing.JRadioButton rbnAbsent;
    private javax.swing.JRadioButton rbnPresent;
    private javax.swing.JTable tblAttendence;
    private javax.swing.JTextField txtAttendenceId;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTime;
    // End of variables declaration//GEN-END:variables

    private void loadData() {
        try {
            dtmAttendence.setRowCount(0);

            ArrayList<AttendenceDTO> all = ctrlattendence.getAll();

            if (all == null) {
                return;
            }

            for (AttendenceDTO attendenceDTO : all) {
                Object[] rowData = {
                    attendenceDTO.getAttend_id(),
                    attendenceDTO.getRid(),
                    attendenceDTO.getSub_id(),
                    attendenceDTO.getDate(),
                    attendenceDTO.getTime(),
                    attendenceDTO.getPresent_mark()

                };
                dtmAttendence.addRow(rowData);
            }
        } catch (Exception ex) {
            Logger.getLogger(Attendence.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void handleEvents() {
        tblAttendence.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent e) {
                try {
                    if (tblAttendence.getSelectedRowCount() <= 0) {
                        return;
                    }

                    String attendenceId = dtmAttendence.getValueAt(tblAttendence.getSelectedRow(), 0).toString();

                    AttendenceDTO attendenceDTO = ctrlattendence.search(attendenceId);

                    if (attendenceDTO != null) {
                        txtAttendenceId.setText(attendenceDTO.getAttend_id());

                    }
                } catch (Exception ex) {
                    Logger.getLogger(Attendence.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
}
