/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.studentmanagementsystem.view;

import com.sun.jmx.snmp.BerDecoder;
import edu.ijse.studentmanagementsystem.controller.ControllerFactory;
import edu.ijse.studentmanagementsystem.controller.custo.GradeController;
import edu.ijse.studentmanagementsystem.dto.GradeDTO;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Krishanthi
 */
public class Grade extends javax.swing.JPanel {

    private GradeController ctrlgrade;
    private DefaultTableModel dtmGrade;
    /**
     * Creates new form Grade
     */
    public Grade() {
        initComponents();
        ctrlgrade=(GradeController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.GRADE);
        dtmGrade= (DefaultTableModel) tblGrade.getModel();
        //view();
        loadData();
        handEvents();
        
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblGrade = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblGradeId = new javax.swing.JLabel();
        txtGradeId = new javax.swing.JTextField();
        lblGradeNo = new javax.swing.JLabel();
        txtGradeNo = new javax.swing.JTextField();
        lblYear = new javax.swing.JLabel();
        txtYear = new javax.swing.JTextField();
        lblStudentLimit = new javax.swing.JLabel();
        txtStudentLimit = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        btnAdd = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        txtsearch = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnRemove = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lblSearch = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGrade = new javax.swing.JTable();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblGrade.setBackground(new java.awt.Color(0, 0, 153));
        lblGrade.setFont(new java.awt.Font("Tempus Sans ITC", 3, 36)); // NOI18N
        lblGrade.setForeground(new java.awt.Color(255, 102, 0));
        lblGrade.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGrade.setText("GRADE");
        lblGrade.setOpaque(true);
        jPanel1.add(lblGrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 40));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jLabel1.setText("Grade");

        lblGradeId.setText("GRADE ID");

        txtGradeId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGradeIdActionPerformed(evt);
            }
        });

        lblGradeNo.setText("GRADE NO");

        lblYear.setText("YEAR");

        txtYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtYearActionPerformed(evt);
            }
        });

        lblStudentLimit.setText("STUDENT LIMIT");

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/studentmanagementsystem/view/linecons_e00f(0)_32.png"))); // NOI18N
        btnAdd.setText("ADD");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        txtsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsearchActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/studentmanagementsystem/view/FontAwesome_f002(0)_32.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addComponent(jSeparator3)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtGradeId)
                    .addComponent(txtGradeNo)
                    .addComponent(txtYear)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblYear, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGradeNo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGradeId, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblStudentLimit, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtStudentLimit)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAdd)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(2, 2, 2)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblGradeId, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtGradeId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblGradeNo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtGradeNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblYear, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblStudentLimit, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtStudentLimit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(btnAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 330, 390));

        btnRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/studentmanagementsystem/view/linecons_e006(0)_32.png"))); // NOI18N
        btnRemove.setText("REMOVE");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });
        jPanel2.add(btnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 450, 150, -1));

        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/studentmanagementsystem/view/Material Icons_e884(0)_32.png"))); // NOI18N
        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel2.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 500, 150, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 204));

        lblSearch.setText("SEARCH");

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });

        tblGrade.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "GRADE ID", "GRADE NO", "YEAR", "STUDENT LIMIT"
            }
        ));
        jScrollPane1.setViewportView(tblGrade);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(408, Short.MAX_VALUE)
                .addComponent(lblSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, 680, 520));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1110, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtGradeIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGradeIdActionPerformed
       
    }//GEN-LAST:event_txtGradeIdActionPerformed

    private void txtYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtYearActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String gradeId = txtGradeId.getText();
        String  gradeNo= txtGradeNo.getText();
        String year = txtYear.getText();
        int studentLimit = Integer.parseInt(txtStudentLimit.getText());
        
        GradeDTO gradeDTO = new GradeDTO(gradeId, gradeNo, year, studentLimit);
        
        try {
            
            boolean add = ctrlgrade.add(gradeDTO);
            if(add){
            
                JOptionPane.showMessageDialog(this, "Success");
                loadData();
            }else{
            
                    JOptionPane.showMessageDialog(this, "something went wrong");
            }
            
        } catch (Exception ex) {
            Logger.getLogger(StudentDetail.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsearchActionPerformed
       String ID=txtSearch.getText();
        
        try {
            GradeDTO gradeDTO = ctrlgrade.search(ID);
            
            if (gradeDTO!=null) {
                
                txtGradeId.setText(gradeDTO.getGradeId());
                txtGradeNo.setText(gradeDTO.getGradeNo());
                txtYear.setText(gradeDTO.getYear());
                txtStudentLimit.setText(""+gradeDTO.getStudentLimit());
                
            } else {
            }
            
        } catch (Exception ex) {
            Logger.getLogger(Grade.class.getName()).log(Level.SEVERE, null, ex);
        }  
    }//GEN-LAST:event_txtsearchActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        String gid= txtSearch.getText();
       try{
           GradeDTO grade = ctrlgrade.search(gid);
           if(grade == null){
               
           }else{
               //System.out.println(grade);
               //Object [] rowData ={course.getCid(),course.getName(),course.getDuration(),course.getFees()};
               Object[] rowData = {
                    grade.getGradeId(),
                    grade.getGradeNo(),
                    grade.getYear(),
                    grade.getStudentLimit()
                    
                };
               
               dtmGrade.setRowCount(0);
               dtmGrade.addRow(rowData);
           }
       } catch (Exception ex) {
            Logger.getLogger(Grade.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_txtSearchActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
         
            String gradeId = dtmGrade.getValueAt(tblGrade.getSelectedRow(),0).toString();
            String gradeNo = dtmGrade.getValueAt(tblGrade.getSelectedRow(),1).toString();
            String year = dtmGrade.getValueAt(tblGrade.getSelectedRow(),2).toString();
            String studentLimit = dtmGrade.getValueAt(tblGrade.getSelectedRow(),3).toString();
            
            GradeDTO gradeDTO=new GradeDTO(gradeId, gradeNo, year, Integer.parseInt(studentLimit));
            try{
            boolean isUpdate=ctrlgrade.update(gradeDTO);
            if(isUpdate){
                JOptionPane.showMessageDialog(Grade.this,"Update Success...");
                loadData();
                //clearFields();
            }else{
                JOptionPane.showMessageDialog(Grade.this,"Update Fail");
            }
        } catch (Exception ex) {
            Logger.getLogger(Grade.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        String gradeId = dtmGrade.getValueAt(tblGrade.getSelectedRow(), 0).toString();
        try {
            boolean deleted = ctrlgrade.delete(gradeId);
            if (deleted) {
                //clearFields();
                //setEnable(false);
                loadData();
                tblGrade.clearSelection();
                //btnNewSubject.requestFocusInWindow();
            } else {

                JOptionPane.showMessageDialog(this,
                        "Grade deletion has been failed, Please try again.",
                        "Delete Error",
                        JOptionPane.ERROR_MESSAGE
                );
            }
        } catch (Exception ex) {

            JOptionPane.showMessageDialog(this,
                    "Grade deletion has been failed, Please try again.",
                    "Delete Error",
                    JOptionPane.ERROR_MESSAGE
            );
            Logger.getLogger(Grade.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRemoveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblGrade;
    private javax.swing.JLabel lblGradeId;
    private javax.swing.JLabel lblGradeNo;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblStudentLimit;
    private javax.swing.JLabel lblYear;
    private javax.swing.JTable tblGrade;
    private javax.swing.JTextField txtGradeId;
    private javax.swing.JTextField txtGradeNo;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtStudentLimit;
    private javax.swing.JTextField txtYear;
    private javax.swing.JTextField txtsearch;
    // End of variables declaration//GEN-END:variables
private void loadData() {

        
        try {
            dtmGrade.setRowCount(0);

            ArrayList<GradeDTO> all = ctrlgrade.getAll();

            if (all == null) {
                return;
            }

            for (GradeDTO gradeDTO : all) {
                Object[] rowData = {
                    gradeDTO.getGradeId(),
                    gradeDTO.getGradeNo(),
                    gradeDTO.getYear(),
                    gradeDTO.getStudentLimit()
               
                };
                dtmGrade.addRow(rowData);
            }
        } catch (Exception ex) {
            Logger.getLogger(Grade.class.getName()).log(Level.SEVERE, null, ex);
        }
    }    

    private void handEvents() {
        tblGrade.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent e) {
                try {
                    if (tblGrade.getSelectedRowCount() <= 0) {
                        return;
                    }
                    
                    String gradeId = dtmGrade.getValueAt(tblGrade.getSelectedRow(), 0).toString();
                    
                    GradeDTO gradeDTO = ctrlgrade.search(gradeId);

                    if (gradeDTO != null) {
                        txtGradeId.setText(gradeDTO.getGradeId());
                        txtGradeNo.setText(gradeDTO.getGradeNo());
                        txtYear.setText(gradeDTO.getYear());
                        txtStudentLimit.setText(""+gradeDTO.getStudentLimit());
                        
                    }
                } catch (Exception ex) {
                    Logger.getLogger(Grade.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

            }
        );
    }
}
