/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.studentmanagementsystem.view;

import edu.ijse.studentmanagementsystem.controller.ControllerFactory;
import edu.ijse.studentmanagementsystem.controller.custo.GradeController;
import edu.ijse.studentmanagementsystem.controller.custo.RegistrationController;
import edu.ijse.studentmanagementsystem.controller.custo.ScheduleController;
import edu.ijse.studentmanagementsystem.controller.custo.SubjectController;
import edu.ijse.studentmanagementsystem.controller.custo.TeacherController;
import edu.ijse.studentmanagementsystem.controller.custom.impl.ScheduleControllerImpl;
import edu.ijse.studentmanagementsystem.dto.GradeDTO;
import edu.ijse.studentmanagementsystem.dto.RegistrationDTO;
import edu.ijse.studentmanagementsystem.dto.ScheduleDTO;
import edu.ijse.studentmanagementsystem.dto.SubjectDTO;
import edu.ijse.studentmanagementsystem.dto.TeacherDTO;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Krishanthi
 */
public class Schedule extends javax.swing.JPanel {

    private SubjectController ctrlsubject;
    private GradeController ctrlgrade;
    private TeacherController ctrlteacher;
    private RegistrationController ctrlregistration;
    private DefaultTableModel dtmSchedule;
    private ScheduleController ctrlschedule;
    /**
     * Creates new form AddExamSchedule
     */
    public Schedule() {
        initComponents();
        ctrlsubject=(SubjectController)ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.SUBJECT);
        ctrlgrade=(GradeController)ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.GRADE);
        ctrlteacher=(TeacherController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.TEACHER);
        ctrlregistration=(RegistrationController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.REGISTRATION);
        loadSubjectIds();
        loadGradeIds();
        loadTeacherIds();
        loadRegisterIds();
        dtmSchedule=(DefaultTableModel) tblSchedule.getModel();
        loadData();
    }
    private void loadSubjectIds(){
        try {
            ArrayList<SubjectDTO>SubjectIdList=ctrlsubject.getAll();
            for(SubjectDTO subjectId:SubjectIdList){
                cmbSubject.addItem(subjectId.getName());
            }
        } catch (Exception e) {
        }
    }
    
    private void loadGradeIds(){
        try {
            ArrayList<GradeDTO>GradeIdList=ctrlgrade.getAll();
            for(GradeDTO gradeId:GradeIdList){
                cmbGrade.addItem(gradeId.getGradeNo());
            }
        } catch (Exception e) {
        }
    }
    private void loadTeacherIds(){
          try {
            ArrayList<TeacherDTO> teacherList=ctrlteacher.getAll();
            for(TeacherDTO teacherDTO:teacherList){
                cmbTeacherName.addItem(teacherDTO.getFull_name());
            }
        } catch (Exception e) {
        }
    }
    private void loadRegisterIds(){
        try {
            ArrayList<RegistrationDTO>registrationList=ctrlregistration.getAll();
            for(RegistrationDTO registrationDTO:registrationList){
                cmbRegisterId.addItem(registrationDTO.getRid());
            }
        } catch (Exception e) {
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblGrade = new javax.swing.JLabel();
        lblSubject = new javax.swing.JLabel();
        lblTeacher = new javax.swing.JLabel();
        lblDay = new javax.swing.JLabel();
        txtDay = new javax.swing.JTextField();
        lblTime = new javax.swing.JLabel();
        txtTime = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        cmbGrade = new javax.swing.JComboBox();
        cmbSubject = new javax.swing.JComboBox();
        lblRegisterId = new javax.swing.JLabel();
        cmbRegisterId = new javax.swing.JComboBox();
        cmbTeacherName = new javax.swing.JComboBox();
        lblScheduleId = new javax.swing.JLabel();
        txtSchedule = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        pnlLoad = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSchedule = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        txtSearch = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1110, 610));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setBackground(new java.awt.Color(0, 0, 153));
        lblTitle.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("SCHEDULE");
        lblTitle.setOpaque(true);
        jPanel1.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 40));

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(1110, 610));

        lblGrade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblGrade.setText("Grade   :");

        lblSubject.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSubject.setText("Subject    :");

        lblTeacher.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTeacher.setText("Teacher Name    :");

        lblDay.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDay.setText("Day    :");

        lblTime.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTime.setText("Time    :");

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/studentmanagementsystem/view/linecons_e00f(0)_32.png"))); // NOI18N
        btnAdd.setText("ADD");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        lblRegisterId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblRegisterId.setText("Register Id");

        lblScheduleId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblScheduleId.setText("Schedule Id:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 4, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAdd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTime, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDay, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRegisterId, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDay, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTime, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbRegisterId, 0, 316, Short.MAX_VALUE)
                            .addComponent(cmbSubject, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbGrade, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbTeacherName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSchedule)
                            .addComponent(lblScheduleId, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(lblScheduleId, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbTeacherName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSubject)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRegisterId, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbRegisterId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDay, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTime, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAdd)
                .addGap(42, 42, 42))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 340, 500));

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/studentmanagementsystem/view/linecons_e006(0)_32.png"))); // NOI18N
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 540, 200, 40));

        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/studentmanagementsystem/view/Material Icons_e884(0)_32.png"))); // NOI18N
        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 480, 200, 40));

        pnlLoad.setBackground(new java.awt.Color(255, 255, 204));
        pnlLoad.setPreferredSize(new java.awt.Dimension(740, 240));

        tblSchedule.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Schedule Id", "Teacher Name", "Grade", "Subject", "Register Id", "Day", "Time"
            }
        ));
        jScrollPane1.setViewportView(tblSchedule);

        javax.swing.GroupLayout pnlLoadLayout = new javax.swing.GroupLayout(pnlLoad);
        pnlLoad.setLayout(pnlLoadLayout);
        pnlLoadLayout.setHorizontalGroup(
            pnlLoadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
            .addGroup(pnlLoadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoadLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        pnlLoadLayout.setVerticalGroup(
            pnlLoadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
            .addGroup(pnlLoadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoadLayout.createSequentialGroup()
                    .addContainerGap(65, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(26, Short.MAX_VALUE)))
        );

        jPanel1.add(pnlLoad, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 740, 350));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 760, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 62, 760, 10));

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        jPanel1.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 80, 217, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/studentmanagementsystem/view/linecons_e009(0)_32.png"))); // NOI18N
        jLabel1.setText("SEARCH");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 80, 40, 22));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String scheduleId=txtSchedule.getText();
        String teacherName=cmbTeacherName.getSelectedItem().toString();
        String grade=cmbGrade.getSelectedItem().toString();
        String sub_id = cmbSubject.getSelectedItem().toString();
        String  rid= cmbRegisterId.getSelectedItem().toString();
        String date = txtDay.getText();
        Double time = (Double.parseDouble(txtTime.getText()));
        
        ScheduleDTO scheduleDTO = new ScheduleDTO(scheduleId,teacherName, grade, sub_id, rid, date, time);
        
        try {
            
            boolean add = ctrlschedule.add(scheduleDTO);
            if(add){
            
                JOptionPane.showMessageDialog(this, "Success");
                loadData();
            }else{
            
                    JOptionPane.showMessageDialog(this, "something went wrong");
            }
            
        } catch (Exception ex) {
            Logger.getLogger(Schedule.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try {
            String scheduleId=txtSchedule.getText();
            String teacherName=cmbTeacherName.getSelectedItem().toString();
            String grade=cmbGrade.getSelectedItem().toString();
            String sub_id = cmbSubject.getSelectedItem().toString();
            String  rid= cmbRegisterId.getSelectedItem().toString();
            String date = txtDay.getText();
            Double time = (Double.parseDouble(txtTime.getText()));
        
        ScheduleDTO scheduleDTO = new ScheduleDTO(scheduleId,teacherName, grade, sub_id, rid, date, time);
        
            boolean isUpdate=ctrlschedule.update(scheduleDTO);
            if(isUpdate){
                JOptionPane.showMessageDialog(Schedule.this,"Update Success...");
                loadData();
                //clearFields();
            }else{
                JOptionPane.showMessageDialog(Schedule.this,"Update Fail");
            }
        } catch (Exception ex) {
            Logger.getLogger(Schedule.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        String scheduleId = dtmSchedule.getValueAt(tblSchedule.getSelectedRow(), 0).toString();
        try {
            boolean deleted = ctrlschedule.delete(scheduleId);
            if (deleted) {
                //clearFields();
                //setEnable(false);
                
                tblSchedule.clearSelection();
                //btnNewSubject.requestFocusInWindow();
                JOptionPane.showMessageDialog(this,"DELETE Success");
            } else {
                JOptionPane.showMessageDialog(this,
                    "Schedule deletion has been failed, Please try again.",
                    "Delete Error",
                    JOptionPane.ERROR_MESSAGE
            );
                
                
            }
        } catch (Exception ex) {

            Logger.getLogger(Schedule.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        String scheduleId= txtSearch.getText();
       try{
           ScheduleDTO schedule = ctrlschedule.search(scheduleId);
           if(schedule == null){
               
           }else{
               
               
                Object[] rowData = {
                    schedule.getScheduleId(),
                    schedule.getGrade(),
                    schedule.getSubject(),
                    schedule.getRegisterId(),
                    schedule.getDay(),
                    schedule.getTime()
                    
                };
               dtmSchedule.setRowCount(0);
               dtmSchedule.addRow(rowData);
           }
       } catch (Exception ex) {
            Logger.getLogger(Schedule.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_txtSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox cmbGrade;
    private javax.swing.JComboBox cmbRegisterId;
    private javax.swing.JComboBox cmbSubject;
    private javax.swing.JComboBox cmbTeacherName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblDay;
    private javax.swing.JLabel lblGrade;
    private javax.swing.JLabel lblRegisterId;
    private javax.swing.JLabel lblScheduleId;
    private javax.swing.JLabel lblSubject;
    private javax.swing.JLabel lblTeacher;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlLoad;
    private javax.swing.JTable tblSchedule;
    private javax.swing.JTextField txtDay;
    private javax.swing.JTextField txtSchedule;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTime;
    // End of variables declaration//GEN-END:variables

    private void loadData() {
        try {
            //dtmSchedule.setRowCount(0);
            ctrlschedule = new ScheduleControllerImpl();
            ArrayList<ScheduleDTO> all = ctrlschedule.getAll();

            if (all == null) {
                return;
            }

            for (ScheduleDTO schedule: all) {
                Object[] rowData = {
                    schedule.getScheduleId(),
                    schedule.getGrade(),
                    schedule.getSubject(),
                    schedule.getRegisterId(),
                    schedule.getDay(),
                    schedule.getTime()
                    
                };
                dtmSchedule.addRow(rowData);
            }
        } catch (Exception ex) {
            Logger.getLogger(Schedule.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
