/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.studentmanagementsystem.view;

import edu.ijse.studentmanagementsystem.controller.ControllerFactory;
import edu.ijse.studentmanagementsystem.controller.custo.GradeController;
import edu.ijse.studentmanagementsystem.controller.custo.RegistrationController;
import edu.ijse.studentmanagementsystem.controller.custo.StudentController;
import edu.ijse.studentmanagementsystem.dao.custom.StudentDAO;
import edu.ijse.studentmanagementsystem.dto.GradeDTO;
import edu.ijse.studentmanagementsystem.dto.RegistrationDTO;
import edu.ijse.studentmanagementsystem.dto.StudentDTO;
import java.awt.Component;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Krishanthi
 */
public class StudentDetail extends javax.swing.JPanel {

    private StudentController ctrlstudent;
    private StudentController ctrlStudent;
    private GradeController ctrlGrade;
    private RegistrationController ctrlRegistration;
    private DefaultTableModel dtmStudent;

    /**
     * Creates new form StudentDetail
     */
    public StudentDetail() {
        initComponents();
        ctrlstudent = (StudentController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.STUDENT);
        ctrlGrade = (GradeController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.GRADE);
        //loadData();
        setDate();
        //dtmStudent= (DefaultTableModel) tblStudent.getModel();
    }

    private void clearFields() {
        txtId.setText("");
        txtFullName.setText("");
        txtDOB.setText("");
        //buttonGroup1.setSelected(null, true);
        txtAddress.setText("");
        txtPhone.setText("");
        txtGuardianName.setText("");
        txtGuardianPhoneNo.setText("");

    }
   
    /* private void doValidate(){
     String studentId=txtId.getText();
     String studentName=txtFullName.getText();
     String studentDOB=txtDOB.getText();
     String studentAddress=txtAddress.getText();
     String studentPhone=txtPhone.getText();
     String studentGuardianName=txtGuardianName.getText();
     String studentgPhone=txtGuardianPhoneNo.getText();
        
     btnAdd.setEnabled(false);
        
     if(!studentId.isEmpty()){
     if(studentName.matches("[A-Za-z]+")){
     if(!studentDOB.isEmpty()){
     if(!studentAddress.isEmpty()){
     if(studentPhone.matches("")){
     if(!studentGuardianName.isEmpty()){
     if(!studentgPhone.isEmpty()){
                                 
     }
     }
     }
     }  
     } 
     }
     }
        
     }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlLoading = new javax.swing.JPanel();
        lblSearchStudent = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lblFullName = new javax.swing.JLabel();
        txtFullName = new javax.swing.JTextField();
        lblDOB = new javax.swing.JLabel();
        txtDOB = new javax.swing.JTextField();
        lblGender = new javax.swing.JLabel();
        rbnMail = new javax.swing.JRadioButton();
        rbnFemail = new javax.swing.JRadioButton();
        lblAddress = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        lblPhone = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        lblGuardian = new javax.swing.JLabel();
        lblGuardianName = new javax.swing.JLabel();
        txtGuardianName = new javax.swing.JTextField();
        lblGphone = new javax.swing.JLabel();
        txtGuardianPhoneNo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtJob = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 153));
        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADD STUDENT DETAIL");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 3, 1090, 30));

        pnlLoading.setBackground(new java.awt.Color(255, 255, 255));

        lblSearchStudent.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSearchStudent.setText("Search Student");

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("DATE");

        lblId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblId.setText("ID");

        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        txtId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIdKeyReleased(evt);
            }
        });

        lblFullName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblFullName.setText("FULL NAME");

        lblDOB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDOB.setText("DADE OF BIRTH");

        txtDOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDOBActionPerformed(evt);
            }
        });

        lblGender.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblGender.setText("GENDER");

        buttonGroup1.add(rbnMail);
        rbnMail.setText("Mail");
        rbnMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnMailActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbnFemail);
        rbnFemail.setText("Femail");
        rbnFemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnFemailActionPerformed(evt);
            }
        });

        lblAddress.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblAddress.setText("ADDRESS");

        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });

        lblPhone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPhone.setText("PHONE NUMBER");

        lblGuardian.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblGuardian.setText("Guardian Details");

        lblGuardianName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblGuardianName.setText("Guardian Name");

        lblGphone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblGphone.setText("Phone Number");

        txtGuardianPhoneNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGuardianPhoneNoActionPerformed(evt);
            }
        });

        jLabel2.setText("jLabel1");

        txtJob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJobActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDelete.setText("DELETE");

        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAdd.setText("ADD");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlLoadingLayout = new javax.swing.GroupLayout(pnlLoading);
        pnlLoading.setLayout(pnlLoadingLayout);
        pnlLoadingLayout.setHorizontalGroup(
            pnlLoadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoadingLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLoadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLoadingLayout.createSequentialGroup()
                        .addGroup(pnlLoadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator3)
                            .addGroup(pnlLoadingLayout.createSequentialGroup()
                                .addGroup(pnlLoadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlLoadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblGuardian, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblGuardianName, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtGuardianName, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                                        .addComponent(txtFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblGender, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblGphone, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtGuardianPhoneNo, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtJob, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                                        .addGroup(pnlLoadingLayout.createSequentialGroup()
                                            .addGap(10, 10, 10)
                                            .addComponent(rbnMail, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(35, 35, 35)
                                            .addComponent(rbnFemail, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(lblAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtAddress)
                                        .addComponent(txtDOB, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                                        .addComponent(txtPhone))
                                    .addGroup(pnlLoadingLayout.createSequentialGroup()
                                        .addComponent(lblSearchStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(346, 346, 346)
                        .addGroup(pnlLoadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoadingLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(184, 184, 184))
        );
        pnlLoadingLayout.setVerticalGroup(
            pnlLoadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoadingLayout.createSequentialGroup()
                .addGroup(pnlLoadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLoadingLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlLoadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoadingLayout.createSequentialGroup()
                        .addContainerGap(36, Short.MAX_VALUE)
                        .addGroup(pnlLoadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSearchStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(pnlLoadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLoadingLayout.createSequentialGroup()
                        .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(lblFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txtFullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(lblDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblGender, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlLoadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbnMail)
                            .addComponent(rbnFemail))
                        .addGap(18, 18, 18)
                        .addComponent(lblAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(lblPhone)
                        .addGap(8, 8, 8)
                        .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblGuardian, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(lblGuardianName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txtGuardianName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblGphone, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txtGuardianPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txtJob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlLoadingLayout.createSequentialGroup()
                        .addGap(386, 386, 386)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41))
        );

        jScrollPane1.setViewportView(pnlLoading);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1110, 570));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 710));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed

        try {                                       
            
            String id = txtId.getText();
            String name = txtFullName.getText();
            String dob = txtDOB.getText();
            String address = txtAddress.getText();
            int phone = Integer.parseInt(txtPhone.getText());
            String guardianName = txtGuardianName.getText();
            String guardianJob = txtJob.getText();
            int guardianPhoneNo = Integer.parseInt(txtGuardianPhoneNo.getText());
            String gender = "";
            
            if (rbnMail.isSelected()) {
                gender = "male";
                
            }
            
            if (rbnFemail.isSelected()) {
                gender = "female";
                
            }
            
            StudentDTO studentDTO = new StudentDTO(id, name, dob, gender, address, phone, guardianName, guardianJob, guardianPhoneNo);
            
            
            boolean add = ctrlstudent.add(studentDTO);
            if (add) {

                JOptionPane.showMessageDialog(this, "Success");
                //loadData();
            } else {

                JOptionPane.showMessageDialog(this, "something went wrong");
            }

            } catch (Exception ex) {
                Logger.getLogger(StudentDetail.class.getName()).log(Level.SEVERE, null, ex);
            }
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
       /* try {                                       
            
            String id = txtId.getText();
            String name = txtFullName.getText();
            String dob = txtDOB.getText();
            String address = txtAddress.getText();
            int phone = Integer.parseInt(txtPhone.getText());
            String guardianName = txtGuardianName.getText();
            String guardianJob = txtJob.getText();
            int guardianPhoneNo = Integer.parseInt(txtGuardianPhoneNo.getText());
            String gender = "";
            
            if (rbnMail.isSelected()) {
                gender = "male";
                
            }
            
            if (rbnFemail.isSelected()) {
                gender = "female";
                
            }
            
            StudentDTO studentDTO = new StudentDTO(id, name, dob, gender, address, phone, guardianName, guardianJob, guardianPhoneNo);
            
        boolean isUpdate = ctrlstudent.update(studentDTO);
            if (isUpdate) {
                JOptionPane.showMessageDialog(StudentDetail.this, "Update Success...");
                //loadData();
                //clearFields();
            } else {
                JOptionPane.showMessageDialog(StudentDetail.this, "Update Fail");
            }
        } catch (Exception ex) {
            Logger.getLogger(StudentDetail.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtJobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJobActionPerformed

    private void txtGuardianPhoneNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGuardianPhoneNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGuardianPhoneNoActionPerformed

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void rbnFemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnFemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnFemailActionPerformed

    private void rbnMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnMailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnMailActionPerformed

    private void txtDOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDOBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDOBActionPerformed

    private void txtIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdKeyReleased
        //doValidate();
    }//GEN-LAST:event_txtIdKeyReleased

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        String ID = txtSearch.getText();

        try {
            StudentDTO student = ctrlstudent.search(ID);
            //System.out.println(student.getFullName());
            if (student != null) {
                txtFullName.setText(student.getFullName());
                txtFullName.setText(student.getFullName());
                txtDOB.setText(student.getDob());

                if (student.getGender().equalsIgnoreCase("male")) {
                    rbnMail.setSelected(true);
                } else {

                    rbnFemail.setSelected(true);
                }

                txtAddress.setText(student.getAddress());
                txtPhone.setText("" + student.getPhoneNo());
                txtGuardianName.setText(student.getGuardianName());
                txtJob.setText(student.getGuardianJob());
                txtGuardianPhoneNo.setText("" + student.getGuardianPhoneNo());
            } else {
            }

        } catch (Exception ex) {
            Logger.getLogger(StudentDetail.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblFullName;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblGphone;
    private javax.swing.JLabel lblGuardian;
    private javax.swing.JLabel lblGuardianName;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblSearchStudent;
    private javax.swing.JPanel pnlLoading;
    private javax.swing.JRadioButton rbnFemail;
    private javax.swing.JRadioButton rbnMail;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtDOB;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JTextField txtGuardianName;
    private javax.swing.JTextField txtGuardianPhoneNo;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtJob;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    private void setDate() {
        java.util.Date d1 = new java.util.Date();
        SimpleDateFormat df = new SimpleDateFormat("YYYY-MM-dd");
        String formatDate = df.format(d1);
        txtDate.setText(formatDate);

    }

   /* private void loadData() {
        try {
            dtmStudent.setRowCount(0);

            ArrayList<StudentDTO> all = ctrlstudent.getAll();

            if (all == null) {
                return;
            }

            for (StudentDTO studentDTO : all) {
                Object[] rowData = {
                    studentDTO.getSid(),
                    studentDTO.getFullName(),
                    studentDTO.getDob(),
                    studentDTO.getGender(),
                    studentDTO.getAddress(),
                    studentDTO.getPhoneNo(),
                    studentDTO.getGuardianName(),
                    studentDTO.getGuardianPhoneNo(),
                    studentDTO.getGuardianJob()

                };
                dtmStudent.addRow(rowData);
            }
        } catch (Exception ex) {
            Logger.getLogger(StudentDetail.class.getName()).log(Level.SEVERE, null, ex);
        }

    }*/
}

