/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.studentmanagementsystem.view;

import edu.ijse.studentmanagementsystem.controller.ControllerFactory;
import edu.ijse.studentmanagementsystem.controller.custo.SubjectController;
import edu.ijse.studentmanagementsystem.controller.custo.TeacherController;
import edu.ijse.studentmanagementsystem.controller.custom.impl.TeacherControllerImpl;
import edu.ijse.studentmanagementsystem.dto.SubjectDTO;
import edu.ijse.studentmanagementsystem.dto.TeacherDTO;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Krishanthi
 */
public class Teacher extends javax.swing.JPanel {

    
    private TeacherController ctrlteacher;
    private SubjectController ctrlsubject;
    private DefaultTableModel dtmTeacher;
    /**
     * Creates new form Teacher
     */
    public Teacher() {
        initComponents();
        ctrlteacher= (TeacherController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.TEACHER);
        ctrlsubject=(SubjectController)ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.SUBJECT);
        dtmTeacher = (DefaultTableModel) tblTeacher.getModel();
        loadSubjectIds();
        loadData();
        //handEvents();
    }
    private void loadSubjectIds(){
        try {
            ArrayList<SubjectDTO> subjectList=ctrlsubject.getAll();
            for(SubjectDTO subjectDTO:subjectList){
                cmbSubjectId.addItem(subjectDTO.getName());
            }
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblTeacherId = new javax.swing.JLabel();
        lblFullName = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblDob = new javax.swing.JLabel();
        txtGender = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblTele = new javax.swing.JLabel();
        txtTeacherId = new javax.swing.JTextField();
        txtFullName = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtDob = new javax.swing.JTextField();
        rbnMale = new javax.swing.JRadioButton();
        rbnFemale = new javax.swing.JRadioButton();
        txtAddress = new javax.swing.JTextField();
        txtTele = new javax.swing.JTextField();
        lblIncome = new javax.swing.JLabel();
        txtIncome = new javax.swing.JTextField();
        lblSybject = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        lblSearch = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        cmbSubjectId = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTeacher = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 153));
        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TEACHER DETAIL");
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 40));

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTeacherId.setText("TEACHER ID");
        jPanel2.add(lblTeacherId, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 25, 114, 25));

        lblFullName.setText("FULL NAME");
        jPanel2.add(lblFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 134, 85, 25));

        lblName.setText("NAME WITH INITIALS");
        jPanel2.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 191, 119, 25));

        lblDob.setText("DOB");
        jPanel2.add(lblDob, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 248, 98, 25));

        txtGender.setText("GENDER");
        jPanel2.add(txtGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 305, 68, 25));

        lblAddress.setText("ADDRESS");
        jPanel2.add(lblAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 357, 76, 25));

        lblTele.setText("TELEPHONE NO");
        jPanel2.add(lblTele, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 414, 95, 25));
        jPanel2.add(txtTeacherId, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 56, 137, -1));
        jPanel2.add(txtFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 165, 386, -1));

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        jPanel2.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 222, 386, -1));

        txtDob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDobActionPerformed(evt);
            }
        });
        jPanel2.add(txtDob, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 279, 386, -1));

        buttonGroup1.add(rbnMale);
        rbnMale.setText("Male");
        rbnMale.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.add(rbnMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 332, -1, -1));

        buttonGroup1.add(rbnFemale);
        rbnFemale.setText("FEMALE");
        rbnFemale.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.add(rbnFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 332, -1, -1));
        jPanel2.add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 388, 386, -1));

        txtTele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTeleActionPerformed(evt);
            }
        });
        jPanel2.add(txtTele, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 445, 386, -1));

        lblIncome.setText("INCOME");
        jPanel2.add(lblIncome, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 471, 106, 20));
        jPanel2.add(txtIncome, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 498, 283, -1));

        lblSybject.setText("SUBJECT ID");
        jPanel2.add(lblSybject, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 82, 85, 20));

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/studentmanagementsystem/view/linecons_e00f(0)_32.png"))); // NOI18N
        btnAdd.setText("ADD");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel2.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 500, -1, -1));

        lblSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/studentmanagementsystem/view/linecons_e009(0)_32.png"))); // NOI18N
        lblSearch.setText("SEARCH");
        jPanel2.add(lblSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 16, 40, -1));

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        jPanel2.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 13, 130, 40));

        jPanel2.add(cmbSubjectId, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 390, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 410, 550));

        tblTeacher.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TEACHER ID", "SUBJECT NAME", "FULL NAME", "NAME WITH INITIALS", "DOB", "GENDER", "ADDRESS", "TELE", "INCOME"
            }
        ));
        jScrollPane1.setViewportView(tblTeacher);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, 640, 300));

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/studentmanagementsystem/view/linecons_e006(0)_32.png"))); // NOI18N
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/studentmanagementsystem/view/Material Icons_e884(0)_32.png"))); // NOI18N
        btnUpdate.setText("UPDATE");

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel2.setText("All Details");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(248, Short.MAX_VALUE)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(352, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 660, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtTeleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTeleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTeleActionPerformed

    private void txtDobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDobActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        String ID=txtSearch.getText();
        
        try {
            TeacherDTO teacher = ctrlteacher.search(ID);
            
            if (teacher!=null) {
                txtTeacherId.setText(teacher.getTid());
                cmbSubjectId.setSelectedItem(teacher.getSub_id());
                txtFullName.setText(teacher.getFull_name());
                txtName.setText(teacher.getName_with_initials());
                txtDob.setText(teacher.getDob());
                
                if (teacher.getGender().equalsIgnoreCase("male")) {
                    rbnMale.setSelected(true);
                }else{
                
                    rbnFemale.setSelected(true);
                }
                
                txtAddress.setText(teacher.getAddress());
                txtTele.setText(""+teacher.getTele());
                txtIncome.setText(""+teacher.getIncome());
                
            } else {
            }
            
        } catch (Exception ex) {
            Logger.getLogger(Teacher.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtSearchActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        try {                                       
            String teacherId=txtTeacherId.getText();
            String subjectID=ctrlsubject.getIdByName(cmbSubjectId.getSelectedItem().toString()).getSub_id();
            String fullName=txtFullName.getText();
            String nameWithInitials=txtName.getText();
            String dob=txtDob.getText();
            String gender=txtGender.getText();
            String address=txtAddress.getText();
            int tele= Integer.parseInt(txtTele.getText());
            Double income=Double.parseDouble(txtIncome.getText());
            
            TeacherDTO teacherDTO=new TeacherDTO(teacherId, subjectID, fullName, nameWithInitials, dob, gender, address, tele, income);
            
            try {
                
                boolean add = ctrlteacher.add(teacherDTO);
                if(add){
                    
                    JOptionPane.showMessageDialog(this, "Success");
                    loadData();
                }else{
                    
                    JOptionPane.showMessageDialog(this, "something went wrong");
                }
                
            } catch (Exception ex) {
                Logger.getLogger(Teacher.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (Exception ex) {
            Logger.getLogger(Teacher.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
         String teacherId = dtmTeacher.getValueAt(tblTeacher.getSelectedRow(), 0).toString();
        try {
            boolean deleted = ctrlteacher.delete(teacherId);
            if (deleted) {
                //clearFields();
                //setEnable(false);
                loadData();
                tblTeacher.clearSelection();
                //btnNewSubject.requestFocusInWindow();
                JOptionPane.showMessageDialog(this, "DELETE Success");
            } else {

              JOptionPane.showMessageDialog(this,
                    "Teacher deletion has been failed, Please try again.",
                    "Delete Error",
                    JOptionPane.ERROR_MESSAGE
            );   

            }
        } catch (Exception ex) {

           
            Logger.getLogger(Teacher.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cmbSubjectId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblDob;
    private javax.swing.JLabel lblFullName;
    private javax.swing.JLabel lblIncome;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblSybject;
    private javax.swing.JLabel lblTeacherId;
    private javax.swing.JLabel lblTele;
    private javax.swing.JRadioButton rbnFemale;
    private javax.swing.JRadioButton rbnMale;
    private javax.swing.JTable tblTeacher;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtDob;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JLabel txtGender;
    private javax.swing.JTextField txtIncome;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTeacherId;
    private javax.swing.JTextField txtTele;
    // End of variables declaration//GEN-END:variables

    private void loadData() {
        
        dtmTeacher.setRowCount(0);
        try {
            ArrayList<TeacherDTO> all = ctrlteacher.getAll();

            if (all == null) {
                return;
            }

            for (TeacherDTO teacherDTO : all) {
                Object[] rowData = {
                    teacherDTO.getTid(),
                    teacherDTO.getSub_id(),
                    teacherDTO.getFull_name(),
                    teacherDTO.getName_with_initials(),
                    teacherDTO.getDob(),
                    teacherDTO.getGender(),
                    teacherDTO.getAddress(),
                    teacherDTO.getTele(),
                    teacherDTO.getIncome()
                    
                };
                dtmTeacher.addRow(rowData);
            }
        } catch (Exception ex) {
            Logger.getLogger(Teacher.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /*private void handEvents() {
        tblTeacher.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent e) {
                try {
                    if (tblTeacher.getSelectedRowCount() <= 0) {
                        return;
                    }
                    
                    String teacherId = dtmTeacher.getValueAt(tblTeacher.getSelectedRow(), 0).toString();
                    
                    TeacherDTO teacherDTO = ctrlteacher.search(teacherId);

                    if (teacherDTO != null) {
                        txtTeacherId.setText(teacherDTO.getTid());
                        //cmbSubjectId
                        txtFullName.setText(teacherDTO.getFull_name());
                        txtName.setText(teacherDTO.getName_with_initials());
                        txtDob.setText(teacherDTO.getDob());
                        txtGender.setText(teacherDTO.getGender());
                        txtAddress.setText(teacherDTO.getAddress());
                        txtTele.setText(""+teacherDTO.getTele());
                        txtIncome.setText(""+teacherDTO.getIncome());
                        
                    }
                } catch (Exception ex) {
                    Logger.getLogger(Teacher.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

            }
        );
    }*/
}
