/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.edu.view.admin;

import java.awt.Color;
import java.text.SimpleDateFormat;

/**
 *
 * @author Krishanthi
 */
public class AdminDashBoard extends javax.swing.JFrame {

    /**
     * Creates new form AdminDashBoard
     */
    public AdminDashBoard() {
        initComponents();
        setDate();
        setTime();
        AdminHome h=new AdminHome();
        pnlLoad.removeAll();
        pnlLoad.repaint();
        pnlLoad.revalidate();
        h.setSize(pnlLoad.getSize());
        pnlLoad.add(h);
        h.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        lblUserDetail = new javax.swing.JLabel();
        lblDesingPaper = new javax.swing.JLabel();
        lblQuestionPage = new javax.swing.JLabel();
        lblResult = new javax.swing.JLabel();
        lblUserHistory = new javax.swing.JLabel();
        lblLogout = new javax.swing.JLabel();
        lblHome = new javax.swing.JLabel();
        pnlLoad = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(153, 153, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(153, 153, 255));
        jLabel2.setFont(new java.awt.Font("Castellar", 2, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(" GURUGEDARA  EDUCATION  CENTER.");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 820, 40));

        lblTime.setFont(new java.awt.Font("Castellar", 0, 24)); // NOI18N
        lblTime.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 60, 150, 30));

        lblDate.setFont(new java.awt.Font("Castellar", 0, 24)); // NOI18N
        lblDate.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 60, 120, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("www.Guragedara .com");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 170, 20));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/edu/images/online.png"))); // NOI18N
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 110));

        jSeparator1.setOpaque(true);
        jPanel4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 1140, -1));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 1160, 110));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        lblUserDetail.setBackground(new java.awt.Color(0, 0, 0));
        lblUserDetail.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lblUserDetail.setForeground(new java.awt.Color(255, 255, 255));
        lblUserDetail.setText("User Detail");
        lblUserDetail.setOpaque(true);
        lblUserDetail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUserDetailMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblUserDetailMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblUserDetailMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblUserDetailMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblUserDetailMouseReleased(evt);
            }
        });

        lblDesingPaper.setBackground(new java.awt.Color(0, 0, 0));
        lblDesingPaper.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lblDesingPaper.setForeground(new java.awt.Color(255, 255, 255));
        lblDesingPaper.setText("Design Paper");
        lblDesingPaper.setOpaque(true);
        lblDesingPaper.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDesingPaperMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblDesingPaperMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblDesingPaperMouseExited(evt);
            }
        });

        lblQuestionPage.setBackground(new java.awt.Color(0, 0, 0));
        lblQuestionPage.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lblQuestionPage.setForeground(new java.awt.Color(255, 255, 255));
        lblQuestionPage.setText("Question Page");
        lblQuestionPage.setOpaque(true);
        lblQuestionPage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQuestionPageMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblQuestionPageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblQuestionPageMouseExited(evt);
            }
        });

        lblResult.setBackground(new java.awt.Color(0, 0, 0));
        lblResult.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lblResult.setForeground(new java.awt.Color(255, 255, 255));
        lblResult.setText("Result");
        lblResult.setOpaque(true);
        lblResult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblResultMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblResultMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblResultMouseExited(evt);
            }
        });

        lblUserHistory.setBackground(new java.awt.Color(0, 0, 0));
        lblUserHistory.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lblUserHistory.setForeground(new java.awt.Color(255, 255, 255));
        lblUserHistory.setText("UserHistory");
        lblUserHistory.setOpaque(true);
        lblUserHistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUserHistoryMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblUserHistoryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblUserHistoryMouseExited(evt);
            }
        });

        lblLogout.setBackground(new java.awt.Color(0, 0, 0));
        lblLogout.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lblLogout.setForeground(new java.awt.Color(255, 255, 255));
        lblLogout.setText("LogOut");
        lblLogout.setOpaque(true);
        lblLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLogoutMouseExited(evt);
            }
        });

        lblHome.setBackground(new java.awt.Color(204, 0, 0));
        lblHome.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lblHome.setForeground(new java.awt.Color(255, 255, 255));
        lblHome.setText("Home");
        lblHome.setOpaque(true);
        lblHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblHomeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblLogout, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblQuestionPage, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(lblUserDetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDesingPaper, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblUserHistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(lblHome, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUserDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDesingPaper, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblQuestionPage, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblResult, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUserHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(221, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 750));

        pnlLoad.setPreferredSize(new java.awt.Dimension(1150, 610));

        javax.swing.GroupLayout pnlLoadLayout = new javax.swing.GroupLayout(pnlLoad);
        pnlLoad.setLayout(pnlLoadLayout);
        pnlLoadLayout.setHorizontalGroup(
            pnlLoadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1150, Short.MAX_VALUE)
        );
        pnlLoadLayout.setVerticalGroup(
            pnlLoadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );

        jPanel3.add(pnlLoad, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblUserDetailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUserDetailMouseClicked
       AllRegistration r=new AllRegistration();
       pnlLoad.removeAll();
       pnlLoad.repaint();
       pnlLoad.revalidate();
       r.setSize(pnlLoad.getSize());
       pnlLoad.add(r);
       r.setVisible(true);
    }//GEN-LAST:event_lblUserDetailMouseClicked

    private void lblDesingPaperMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDesingPaperMouseClicked
       pnlLoad.removeAll();
       ExamPaper d=new ExamPaper();
       d.setSize(pnlLoad.getSize());
       pnlLoad.add(d);
       pnlLoad.updateUI();
    }//GEN-LAST:event_lblDesingPaperMouseClicked

    private void lblQuestionPageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuestionPageMouseClicked
       ManagePaper m=new ManagePaper();
       pnlLoad.removeAll();
       pnlLoad.repaint();
       pnlLoad.revalidate();
       m.setSize(pnlLoad.getSize());
       pnlLoad.add(m);
       m.setVisible(true);
    }//GEN-LAST:event_lblQuestionPageMouseClicked

    private void lblResultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblResultMouseClicked
       AllExamResult r=new AllExamResult();
       pnlLoad.removeAll();
       pnlLoad.repaint();
       pnlLoad.revalidate();
       r.setSize(pnlLoad.getSize());
       pnlLoad.add(r);
       r.setVisible(true);
    }//GEN-LAST:event_lblResultMouseClicked

    private void lblUserHistoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUserHistoryMouseClicked
       UserLoginHistory u=new UserLoginHistory();
       pnlLoad.removeAll();
       pnlLoad.repaint();
       pnlLoad.revalidate();
       u.setSize(pnlLoad.getSize());
       pnlLoad.add(u);
       u.setVisible(true);
    }//GEN-LAST:event_lblUserHistoryMouseClicked

    private void lblUserDetailMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUserDetailMouseEntered
        lblUserDetail.setBackground(Color.DARK_GRAY);
        lblUserDetail.setForeground(Color.gray);
    }//GEN-LAST:event_lblUserDetailMouseEntered

    private void lblUserDetailMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUserDetailMouseExited
        lblUserDetail.setBackground(Color.BLACK);
        lblUserDetail.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblUserDetailMouseExited

    private void lblDesingPaperMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDesingPaperMouseEntered
        lblDesingPaper.setBackground(Color.DARK_GRAY);
        lblDesingPaper.setForeground(Color.gray);
    }//GEN-LAST:event_lblDesingPaperMouseEntered

    private void lblDesingPaperMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDesingPaperMouseExited
        lblDesingPaper.setBackground(Color.BLACK);
        lblDesingPaper.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblDesingPaperMouseExited

    private void lblQuestionPageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuestionPageMouseEntered
        lblQuestionPage.setBackground(Color.DARK_GRAY);
        lblQuestionPage.setForeground(Color.gray);
    }//GEN-LAST:event_lblQuestionPageMouseEntered

    private void lblQuestionPageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuestionPageMouseExited
        lblQuestionPage.setBackground(Color.BLACK);
        lblQuestionPage.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblQuestionPageMouseExited

    private void lblResultMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblResultMouseEntered
        lblResult.setBackground(Color.DARK_GRAY);
        lblResult.setForeground(Color.gray);
    }//GEN-LAST:event_lblResultMouseEntered

    private void lblResultMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblResultMouseExited
        lblResult.setBackground(Color.BLACK);
        lblResult.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblResultMouseExited

    private void lblUserHistoryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUserHistoryMouseEntered
        lblUserHistory.setBackground(Color.DARK_GRAY);
        lblUserHistory.setForeground(Color.gray);
    }//GEN-LAST:event_lblUserHistoryMouseEntered

    private void lblUserHistoryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUserHistoryMouseExited
        lblUserHistory.setBackground(Color.BLACK);
        lblUserHistory.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblUserHistoryMouseExited

    private void lblLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseEntered
        lblLogout.setBackground(Color.DARK_GRAY);
        lblLogout.setForeground(Color.gray);
    }//GEN-LAST:event_lblLogoutMouseEntered

    private void lblLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseExited
        lblLogout.setBackground(Color.BLACK);
        lblLogout.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblLogoutMouseExited

    private void lblHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseEntered
        lblHome.setBackground(Color.red);
        lblHome.setForeground(Color.DARK_GRAY);
    }//GEN-LAST:event_lblHomeMouseEntered

    private void lblHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseExited
        //lblHome.setBackground(Color.red);
        lblHome.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblHomeMouseExited

    private void lblUserDetailMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUserDetailMousePressed
//        lblUserDetail.setBackground(Color.DARK_GRAY);
//        lblUserDetail.setForeground(Color.gray);
    }//GEN-LAST:event_lblUserDetailMousePressed

    private void lblUserDetailMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUserDetailMouseReleased
//        lblUserDetail.setBackground(Color.BLACK);
//        lblUserDetail.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblUserDetailMouseReleased

    private void lblHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseClicked
       AdminHome h=new AdminHome();
       pnlLoad.removeAll();
       pnlLoad.repaint();
       pnlLoad.revalidate();
       h.setSize(pnlLoad.getSize());
       pnlLoad.add(h);
       h.setVisible(true);
    }//GEN-LAST:event_lblHomeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDesingPaper;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel lblQuestionPage;
    private javax.swing.JLabel lblResult;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblUserDetail;
    private javax.swing.JLabel lblUserHistory;
    public static javax.swing.JPanel pnlLoad;
    // End of variables declaration//GEN-END:variables

    private void setDate() {
        java.util.Date d=new java.util.Date();
        SimpleDateFormat df=new SimpleDateFormat("YYYY-MM-dd");
        String formateDate=df.format(d);
        lblTime.setText(formateDate);
    }

    private void setTime() {
        java.util.Date t=new java.util.Date();
        SimpleDateFormat df=new SimpleDateFormat("HH:mm:ss");
        String formateDate=df.format(t);
        lblDate.setText(formateDate);
    }
}
