/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.edu.view.admin;

/**
 *
 * @author Krishanthi
 */
public class AdminDash extends javax.swing.JFrame {

    /**
     * Creates new form AdminDash
     */
    public AdminDash() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlLoad = new javax.swing.JPanel();
        pnlButton = new javax.swing.JPanel();
        lblUserDetail = new javax.swing.JLabel();
        lblUserHistory = new javax.swing.JLabel();
        lblQuestionPage = new javax.swing.JLabel();
        lblResult = new javax.swing.JLabel();
        lblResultPage = new javax.swing.JLabel();
        lblDesignPaper = new javax.swing.JLabel();
        lblHome = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();
        lblMainImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMinimumSize(new java.awt.Dimension(1375, 700));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlLoad.setPreferredSize(new java.awt.Dimension(1150, 610));

        javax.swing.GroupLayout pnlLoadLayout = new javax.swing.GroupLayout(pnlLoad);
        pnlLoad.setLayout(pnlLoadLayout);
        pnlLoadLayout.setHorizontalGroup(
            pnlLoadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1140, Short.MAX_VALUE)
        );
        pnlLoadLayout.setVerticalGroup(
            pnlLoadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );

        jPanel1.add(pnlLoad, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 1140, 610));

        pnlButton.setBackground(new java.awt.Color(51, 51, 51));
        pnlButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUserDetail.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblUserDetail.setForeground(new java.awt.Color(255, 255, 255));
        lblUserDetail.setText("User Detail");
        lblUserDetail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUserDetailMouseClicked(evt);
            }
        });
        pnlButton.add(lblUserDetail, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 220, 70));

        lblUserHistory.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblUserHistory.setForeground(new java.awt.Color(255, 255, 255));
        lblUserHistory.setText("User History");
        lblUserHistory.setMaximumSize(new java.awt.Dimension(64, 18));
        lblUserHistory.setMinimumSize(new java.awt.Dimension(64, 18));
        lblUserHistory.setPreferredSize(new java.awt.Dimension(64, 18));
        lblUserHistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUserHistoryMouseClicked(evt);
            }
        });
        pnlButton.add(lblUserHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 220, 70));

        lblQuestionPage.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblQuestionPage.setForeground(new java.awt.Color(255, 255, 255));
        lblQuestionPage.setText("Question Page");
        lblQuestionPage.setMaximumSize(new java.awt.Dimension(64, 18));
        lblQuestionPage.setMinimumSize(new java.awt.Dimension(64, 18));
        lblQuestionPage.setPreferredSize(new java.awt.Dimension(64, 18));
        lblQuestionPage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQuestionPageMouseClicked(evt);
            }
        });
        pnlButton.add(lblQuestionPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 220, 70));

        lblResult.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblResult.setForeground(new java.awt.Color(255, 255, 255));
        lblResult.setText("Result");
        lblResult.setMaximumSize(new java.awt.Dimension(64, 14));
        lblResult.setMinimumSize(new java.awt.Dimension(64, 14));
        lblResult.setPreferredSize(new java.awt.Dimension(64, 14));
        lblResult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblResultMouseClicked(evt);
            }
        });
        pnlButton.add(lblResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 220, 70));

        lblResultPage.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblResultPage.setForeground(new java.awt.Color(255, 255, 255));
        lblResultPage.setText("Result Page");
        lblResultPage.setMaximumSize(new java.awt.Dimension(64, 14));
        lblResultPage.setMinimumSize(new java.awt.Dimension(64, 14));
        lblResultPage.setPreferredSize(new java.awt.Dimension(64, 14));
        lblResultPage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblResultPageMouseClicked(evt);
            }
        });
        pnlButton.add(lblResultPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 220, 70));

        lblDesignPaper.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblDesignPaper.setForeground(new java.awt.Color(255, 255, 255));
        lblDesignPaper.setText("DesignPaper");
        lblDesignPaper.setMaximumSize(new java.awt.Dimension(64, 14));
        lblDesignPaper.setMinimumSize(new java.awt.Dimension(64, 14));
        lblDesignPaper.setPreferredSize(new java.awt.Dimension(64, 14));
        lblDesignPaper.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDesignPaperMouseClicked(evt);
            }
        });
        pnlButton.add(lblDesignPaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 220, 70));

        lblHome.setBackground(new java.awt.Color(0, 204, 204));
        lblHome.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblHome.setForeground(new java.awt.Color(204, 204, 204));
        lblHome.setText("Home");
        lblHome.setOpaque(true);
        pnlButton.add(lblHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 220, 50));

        lblImage.setBackground(new java.awt.Color(0, 0, 0));
        lblImage.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblImage.setForeground(new java.awt.Color(255, 255, 255));
        lblImage.setText("GURUGEDARA");
        lblImage.setOpaque(true);
        pnlButton.add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 91));

        jPanel1.add(pnlButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 700));

        lblMainImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/edu/images/line_shadow_stripes_shape_black_red_16139_1600x900.jpg"))); // NOI18N
        jPanel1.add(lblMainImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 1140, 90));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1360, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblResultPageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblResultPageMouseClicked
       AllExamResult r=new AllExamResult();
       pnlLoad.removeAll();
       pnlLoad.repaint();
       pnlLoad.revalidate();
       r.setSize(pnlLoad.getSize());
       pnlLoad.add(r);
       r.setVisible(true);
    }//GEN-LAST:event_lblResultPageMouseClicked

    private void lblDesignPaperMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDesignPaperMouseClicked
       DesignPaper d=new DesignPaper();
       pnlLoad.removeAll();
       pnlLoad.repaint();
       pnlLoad.revalidate();
       d.setSize(pnlLoad.getSize());
       pnlLoad.add(d);
       d.setVisible(true);
    }//GEN-LAST:event_lblDesignPaperMouseClicked

    private void lblQuestionPageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuestionPageMouseClicked
       ManagePaper m=new ManagePaper();
       pnlLoad.removeAll();
       pnlLoad.repaint();
       pnlLoad.revalidate();
       m.setSize(pnlLoad.getSize());
       pnlLoad.add(m);
       m.setVisible(true);
    }//GEN-LAST:event_lblQuestionPageMouseClicked

    private void lblResultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblResultMouseClicked
       AllExamResult r=new AllExamResult();
       pnlLoad.removeAll();
       pnlLoad.repaint();
       pnlLoad.revalidate();
       r.setSize(pnlLoad.getSize());
       pnlLoad.add(r);
       r.setVisible(true);
    }//GEN-LAST:event_lblResultMouseClicked

    private void lblUserDetailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUserDetailMouseClicked
       AllRegistration r=new AllRegistration();
       pnlLoad.removeAll();
       pnlLoad.repaint();
       pnlLoad.revalidate();
       r.setSize(pnlLoad.getSize());
       pnlLoad.add(r);
       r.setVisible(true);
    }//GEN-LAST:event_lblUserDetailMouseClicked

    private void lblUserHistoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUserHistoryMouseClicked
       UserLoginHistory r=new UserLoginHistory();
       pnlLoad.removeAll();
       pnlLoad.repaint();
       pnlLoad.revalidate();
       r.setSize(pnlLoad.getSize());
       pnlLoad.add(r);
       r.setVisible(true);
    }//GEN-LAST:event_lblUserHistoryMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDesignPaper;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblMainImage;
    private javax.swing.JLabel lblQuestionPage;
    private javax.swing.JLabel lblResult;
    private javax.swing.JLabel lblResultPage;
    private javax.swing.JLabel lblUserDetail;
    private javax.swing.JLabel lblUserHistory;
    private javax.swing.JPanel pnlButton;
    private javax.swing.JPanel pnlLoad;
    // End of variables declaration//GEN-END:variables
}
