/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.edu.view.admin;

import java.rmi.RemoteException;
import java.rmi.server.UnicastRemoteObject;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import lk.ijse.edu.controller.RegistrationController;
import lk.ijse.edu.controller.StudentController;
import lk.ijse.edu.dto.RegistrationDTO;
import lk.ijse.edu.dto.StudentDTO;
import lk.ijse.edu.observer.Observer;

/**
 *
 * @author Krishanthi
 */
public class AllRegistration extends javax.swing.JPanel implements Observer{

    /**
     * Creates new form AllRegistration
     */
    public AllRegistration() {
        initComponents();
        LoadToTable();
        try {
            UnicastRemoteObject.exportObject(this, 0);
            RegistrationController.getSubject().registerObserver(this);
            //SubjectController.getSubject().registerObserver(this);
        } catch (RemoteException ex) {
            Logger.getLogger(AllRegistration.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(AllRegistration.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblRefashButton = new javax.swing.JLabel();
        lblSearhIcon = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAllStudent = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRefashButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblRefashButton.setForeground(new java.awt.Color(255, 255, 255));
        lblRefashButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/edu/images/octicons_f087(6)_48.png"))); // NOI18N
        lblRefashButton.setText("Refash");
        jPanel1.add(lblRefashButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 0, 123, 45));

        lblSearhIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/edu/images/linecons_e009(0)_48_1.png"))); // NOI18N
        jPanel1.add(lblSearhIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 80, 50));
        jPanel1.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 260, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel2.setText("Admin >>ViewRegistrationPage");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 0, 190, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/edu/images/search12.png"))); // NOI18N
        jLabel3.setMaximumSize(new java.awt.Dimension(704, 84));
        jLabel3.setMinimumSize(new java.awt.Dimension(704, 84));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 700, 50));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/edu/images/FontAwesome_f06e(1)_56.png"))); // NOI18N
        jLabel1.setText("View All Register Student.");
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 46));

        tblAllStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIC", "Student Name", "Mobile No", "Address", "Gender", "Email", "UserName", "Password"
            }
        ));
        jScrollPane1.setViewportView(tblAllStudent);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 122, 1080, 440));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1118, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 508, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 1120, 510));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 1120, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblRefashButton;
    private javax.swing.JLabel lblSearhIcon;
    private javax.swing.JTable tblAllStudent;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    private void LoadToTable() {
        DefaultTableModel dtm = (DefaultTableModel) tblAllStudent.getModel();
        dtm.setRowCount(0);
        
        try {
            List<StudentDTO>students = StudentController.getAllStudents();
            //List<RegistrationDTO>registrations = RegistrationController.getAllRegistrations();
            if(students == null){
                return;
            }
            for (StudentDTO studentDTO : students) {
                Object[]rowData ={
                    //registrationDTO.getIndexNumber(),
                    studentDTO.getNic(),
                    studentDTO.getName(),
                    studentDTO.getMobileNumber(),
                    studentDTO.getAddress(),
                    studentDTO.getGender(),
                    studentDTO.getEmailAddress(),
                    studentDTO.getUserName(),
                    studentDTO.getPassword()
                };
            
                dtm.addRow(rowData);
            }
        } catch (Exception e) {
        }
    }

    @Override
    public void updateObservers() throws Exception {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
