/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.edu.view.user;

import java.rmi.RemoteException;
import java.rmi.server.UnicastRemoteObject;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import lk.ijse.edu.controller.RegistrationController;
import lk.ijse.edu.controller.StudentController;
import lk.ijse.edu.controller.SubjectController;
import lk.ijse.edu.dto.RegistrationDTO;
import lk.ijse.edu.dto.StudentDTO;
import lk.ijse.edu.dto.SubjectDTO;
import lk.ijse.edu.observer.Observer;

/**
 *
 * @author Krishanthi
 */
public class RegisterNow extends javax.swing.JFrame implements Observer {

    private SubjectController subjectController;
    /**
     * Creates new form RegisterNow
     */
    public RegisterNow() {
        initComponents();
        setLocationRelativeTo(null);
        try {
            loadSubject();
            //loadPapers();
            UnicastRemoteObject.exportObject(this, 0);
            RegistrationController.getSubject().registerObserver(this);
            //StudentController.getSubject().registerObserver(this);
            SubjectController.getSubject().registerObserver(this);
        } catch (RemoteException ex) {
            Logger.getLogger(RegisterNow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(RegisterNow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        txtIndexNo = new javax.swing.JTextField();
        txtSID = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        lblIndexNo = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        txtUserName = new javax.swing.JTextField();
        lblUserName = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        txtEmail = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtMobileNumber = new javax.swing.JTextField();
        lblMobileNumber = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        txtNIC = new javax.swing.JTextField();
        lblNIC = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        btnRegister = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        lblEmail1 = new javax.swing.JLabel();
        lblMobileNumber1 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        rbtnFemale = new javax.swing.JRadioButton();
        rbtnMale = new javax.swing.JRadioButton();
        lblSubject = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        cmbSubject = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtIndexNo.setBackground(new java.awt.Color(102, 102, 102));
        txtIndexNo.setForeground(new java.awt.Color(255, 255, 255));
        txtIndexNo.setBorder(null);
        jPanel1.add(txtIndexNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 550, 310, 30));

        txtSID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSIDActionPerformed(evt);
            }
        });
        jPanel1.add(txtSID, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 60, -1));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 580, 310, 10));

        lblIndexNo.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        lblIndexNo.setForeground(new java.awt.Color(255, 255, 255));
        lblIndexNo.setText("Index Number");
        jPanel1.add(lblIndexNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 100, 20));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 500, 310, 10));

        lblPassword.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword.setText("Password");
        jPanel1.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 90, 20));

        txtPassword.setBackground(new java.awt.Color(102, 102, 102));
        txtPassword.setForeground(new java.awt.Color(255, 255, 255));
        txtPassword.setBorder(null);
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 470, 310, 30));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, 310, 10));

        txtUserName.setBackground(new java.awt.Color(102, 102, 102));
        txtUserName.setForeground(new java.awt.Color(255, 255, 255));
        txtUserName.setBorder(null);
        jPanel1.add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 310, 30));

        lblUserName.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        lblUserName.setForeground(new java.awt.Color(255, 255, 255));
        lblUserName.setText("User Name");
        jPanel1.add(lblUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 90, 20));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, 310, 10));

        txtEmail.setBackground(new java.awt.Color(102, 102, 102));
        txtEmail.setForeground(new java.awt.Color(255, 255, 255));
        txtEmail.setBorder(null);
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 310, 30));

        lblEmail.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail.setText("Email Address");
        jPanel1.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 90, 20));

        txtMobileNumber.setBackground(new java.awt.Color(102, 102, 102));
        txtMobileNumber.setForeground(new java.awt.Color(255, 255, 255));
        txtMobileNumber.setBorder(null);
        jPanel1.add(txtMobileNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 310, 30));

        lblMobileNumber.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        lblMobileNumber.setForeground(new java.awt.Color(255, 255, 255));
        lblMobileNumber.setText("Mobile Number");
        jPanel1.add(lblMobileNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 90, 20));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 310, 10));

        lblName.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("Name");
        jPanel1.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 90, 20));

        txtName.setBackground(new java.awt.Color(102, 102, 102));
        txtName.setForeground(new java.awt.Color(255, 255, 255));
        txtName.setBorder(null);
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 310, 30));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 310, 10));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 310, 10));

        txtNIC.setBackground(new java.awt.Color(102, 102, 102));
        txtNIC.setForeground(new java.awt.Color(255, 255, 255));
        txtNIC.setBorder(null);
        jPanel1.add(txtNIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 310, 30));

        lblNIC.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        lblNIC.setForeground(new java.awt.Color(255, 255, 255));
        lblNIC.setText("NIC");
        jPanel1.add(lblNIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 90, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("User >> RegistrationPage");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 170, 20));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 280, 10));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 460, 10));

        jLabel4.setFont(new java.awt.Font("Castellar", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("REGISTER NOW.");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 290, 50));

        jLabel2.setBackground(new java.awt.Color(204, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/edu/images/online_exm.jpg"))); // NOI18N
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 460, 160));

        btnCancel.setText("CANCEL");
        jPanel1.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 630, 220, 30));

        btnRegister.setText("REGISTER");
        btnRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegisterMouseClicked(evt);
            }
        });
        jPanel1.add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 630, 220, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Gurugedara @ gmail.com");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 670, 460, 20));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 620, 460, 10));

        lblEmail1.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        lblEmail1.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail1.setText("Gender");
        jPanel1.add(lblEmail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 90, 20));

        lblMobileNumber1.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        lblMobileNumber1.setForeground(new java.awt.Color(255, 255, 255));
        lblMobileNumber1.setText("Address");
        jPanel1.add(lblMobileNumber1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 90, 20));

        txtAddress.setBackground(new java.awt.Color(102, 102, 102));
        txtAddress.setForeground(new java.awt.Color(255, 255, 255));
        txtAddress.setBorder(null);
        jPanel1.add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 310, 30));
        jPanel1.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 310, 10));

        buttonGroup1.add(rbtnFemale);
        rbtnFemale.setText("female");
        jPanel1.add(rbtnFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, 140, 30));

        buttonGroup1.add(rbtnMale);
        rbtnMale.setText("male");
        jPanel1.add(rbtnMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 150, 30));

        lblSubject.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        lblSubject.setForeground(new java.awt.Color(255, 255, 255));
        lblSubject.setText("Subject");
        jPanel1.add(lblSubject, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 100, 20));
        jPanel1.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 540, 310, 10));

        jPanel1.add(cmbSubject, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 510, 310, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/edu/images/123321.jpg"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegisterMouseClicked
        try {
            int studentId = Integer.parseInt(txtSID.getText());
            String nic = txtNIC.getText();
            String name = txtName.getText();
            String mobileNumber = txtMobileNumber.getText();
            String address = txtAddress.getText();
            String gender = null;
            if (buttonGroup1.isSelected(rbtnMale.getModel())) {
                gender = rbtnMale.getText();
            } else {
                gender = rbtnFemale.getText();
            }
            String emailAddress = txtEmail.getText();
            String userName = txtUserName.getText();
            String password = txtPassword.getText();
            String indexNo = txtIndexNo.getText();
            int id = Integer.parseInt(cmbSubject.getSelectedItem().toString());

            SubjectDTO subjectDTO = new SubjectDTO();
            subjectDTO.setSubjectId(id);
            subjectDTO = SubjectController.serchSubject(subjectDTO);

            StudentDTO studentDTO = new StudentDTO(studentId, nic, name, mobileNumber, address, gender, emailAddress, userName, password);

            RegistrationDTO registrationDTO = new RegistrationDTO();
            registrationDTO.setIndexNumber(indexNo);
//            
//            RegistrationDTO registration = new RegistrationDTO();
            
            
//            registration.setStudentDTO(studentDTO);
//            registration.setSubjectDTO(subjectDTO);

            boolean isAdded = RegistrationController.addRegistration(registrationDTO,studentDTO,subjectDTO);
            //boolean isAdded2 = StudentController.addStudent(studentDTO);

            if (isAdded) {
                JOptionPane.showMessageDialog(this, "Student Registration Added Sucsses");
            } else {
                JOptionPane.showMessageDialog(this, "Student Registration Added Fail");
            }

        } catch (Exception ex) {
            Logger.getLogger(RegisterNow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRegisterMouseClicked

    private void txtSIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterNow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterNow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterNow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterNow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterNow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnRegister;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cmbSubject;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmail1;
    private javax.swing.JLabel lblIndexNo;
    private javax.swing.JLabel lblMobileNumber;
    private javax.swing.JLabel lblMobileNumber1;
    private javax.swing.JLabel lblNIC;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblSubject;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JRadioButton rbtnFemale;
    private javax.swing.JRadioButton rbtnMale;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtIndexNo;
    private javax.swing.JTextField txtMobileNumber;
    private javax.swing.JTextField txtNIC;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtSID;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables

    @Override
    public void updateObservers() throws Exception {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void loadSubject() {
        try {
           List<SubjectDTO>all = subjectController.getAllSubjects();
            cmbSubject.removeAll();
            
            for (SubjectDTO all1 : all) {
                cmbSubject.addItem(all1.getSubjectId());
            }
        } catch (Exception e) {
            Logger.getLogger(RegisterNow.class.getName()).log(Level.SEVERE,null,e);
        }
    }
}
