/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.edu.view.user;

import java.awt.Color;
import java.text.SimpleDateFormat;

/**
 *
 * @author Krishanthi
 */
public class UserDash extends javax.swing.JFrame {

    /**
     * Creates new form UserDash
     */
    public UserDash() {
        initComponents();
        setDate();
        setTime();
        Home h=new Home();
        pnlLoad.removeAll();
        pnlLoad.repaint();
        pnlLoad.revalidate();
        h.setSize(pnlLoad.getSize());
        pnlLoad.add(h);
        h.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblTime = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblHome = new javax.swing.JLabel();
        lblExam = new javax.swing.JLabel();
        lblResult = new javax.swing.JLabel();
        lblUserSetting = new javax.swing.JLabel();
        lblLogOut = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        pnlLoad = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTime.setFont(new java.awt.Font("Castellar", 0, 24)); // NOI18N
        lblTime.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 50, 180, 30));

        lblDate.setFont(new java.awt.Font("Castellar", 0, 24)); // NOI18N
        lblDate.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 50, 140, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("www.Gurugadara .com");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 160, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/edu/images/online.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 130));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHome.setBackground(new java.awt.Color(204, 0, 0));
        lblHome.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lblHome.setForeground(new java.awt.Color(255, 255, 255));
        lblHome.setText("Home");
        lblHome.setOpaque(true);
        lblHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHomeMouseClicked(evt);
            }
        });
        jPanel4.add(lblHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 40));

        lblExam.setBackground(new java.awt.Color(0, 0, 0));
        lblExam.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lblExam.setForeground(new java.awt.Color(255, 255, 255));
        lblExam.setText("Exam");
        lblExam.setOpaque(true);
        lblExam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExamMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblExamMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblExamMouseExited(evt);
            }
        });
        jPanel4.add(lblExam, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 140, 40));

        lblResult.setBackground(new java.awt.Color(0, 0, 0));
        lblResult.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lblResult.setForeground(new java.awt.Color(255, 255, 255));
        lblResult.setText("Result");
        lblResult.setOpaque(true);
        lblResult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblResultMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblResultMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblResultMouseExited(evt);
            }
        });
        jPanel4.add(lblResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 150, 40));

        lblUserSetting.setBackground(new java.awt.Color(0, 0, 0));
        lblUserSetting.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lblUserSetting.setForeground(new java.awt.Color(255, 255, 255));
        lblUserSetting.setText("User Setting");
        lblUserSetting.setOpaque(true);
        lblUserSetting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUserSettingMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblUserSettingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblUserSettingMouseExited(evt);
            }
        });
        jPanel4.add(lblUserSetting, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 130, 40));

        lblLogOut.setBackground(new java.awt.Color(0, 0, 0));
        lblLogOut.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lblLogOut.setForeground(new java.awt.Color(255, 255, 255));
        lblLogOut.setText("LogOut");
        lblLogOut.setOpaque(true);
        lblLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogOutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLogOutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLogOutMouseExited(evt);
            }
        });
        jPanel4.add(lblLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, 140, 40));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 1030, 40));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 300, -1));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 1030, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 130));

        pnlLoad.setPreferredSize(new java.awt.Dimension(1360, 550));

        javax.swing.GroupLayout pnlLoadLayout = new javax.swing.GroupLayout(pnlLoad);
        pnlLoad.setLayout(pnlLoadLayout);
        pnlLoadLayout.setHorizontalGroup(
            pnlLoadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1360, Short.MAX_VALUE)
        );
        pnlLoadLayout.setVerticalGroup(
            pnlLoadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );

        jPanel1.add(pnlLoad, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblExamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExamMouseEntered
        lblExam.setBackground(Color.DARK_GRAY);
        lblExam.setForeground(Color.gray);
    }//GEN-LAST:event_lblExamMouseEntered

    private void lblExamMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExamMouseExited
        lblExam.setBackground(Color.BLACK);
        lblExam.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblExamMouseExited

    private void lblResultMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblResultMouseEntered
        lblResult.setBackground(Color.DARK_GRAY);
        lblResult.setForeground(Color.gray);
    }//GEN-LAST:event_lblResultMouseEntered

    private void lblResultMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblResultMouseExited
        lblResult.setBackground(Color.BLACK);
        lblResult.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblResultMouseExited

    private void lblUserSettingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUserSettingMouseEntered
        lblUserSetting.setBackground(Color.DARK_GRAY);
        lblUserSetting.setForeground(Color.gray);
    }//GEN-LAST:event_lblUserSettingMouseEntered

    private void lblUserSettingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUserSettingMouseExited
        lblUserSetting.setBackground(Color.BLACK);
        lblUserSetting.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblUserSettingMouseExited

    private void lblLogOutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogOutMouseEntered
        lblLogOut.setBackground(Color.DARK_GRAY);
        lblLogOut.setForeground(Color.gray);
    }//GEN-LAST:event_lblLogOutMouseEntered

    private void lblLogOutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogOutMouseExited
        lblLogOut.setBackground(Color.BLACK);
        lblLogOut.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblLogOutMouseExited

    private void lblExamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExamMouseClicked
       ExamPaper ep=new ExamPaper();
       pnlLoad.removeAll();
       pnlLoad.repaint();
       pnlLoad.revalidate();
       ep.setSize(pnlLoad.getSize());
       pnlLoad.add(ep);
       ep.setVisible(true);
    }//GEN-LAST:event_lblExamMouseClicked

    private void lblResultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblResultMouseClicked
       Result r=new Result();
       pnlLoad.removeAll();
       pnlLoad.repaint();
       pnlLoad.revalidate();
       r.setSize(pnlLoad.getSize());
       pnlLoad.add(r);
       r.setVisible(true);
    }//GEN-LAST:event_lblResultMouseClicked

    private void lblUserSettingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUserSettingMouseClicked
       UserSetting us=new UserSetting();
       pnlLoad.removeAll();
       pnlLoad.repaint();
       pnlLoad.revalidate();
       us.setSize(pnlLoad.getSize());
       pnlLoad.add(us);
       us.setVisible(true);
    }//GEN-LAST:event_lblUserSettingMouseClicked

    private void lblLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogOutMouseClicked
       UserLogin login=new UserLogin();
       login.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_lblLogOutMouseClicked

    private void lblHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseClicked
       Home h=new Home();
       pnlLoad.removeAll();
       pnlLoad.repaint();
       pnlLoad.revalidate();
       h.setSize(pnlLoad.getSize());
       pnlLoad.add(h);
       h.setVisible(true);
    }//GEN-LAST:event_lblHomeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserDash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblExam;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblLogOut;
    private javax.swing.JLabel lblResult;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblUserSetting;
    private javax.swing.JPanel pnlLoad;
    // End of variables declaration//GEN-END:variables

    private void setDate() {
        java.util.Date d=new java.util.Date();
        SimpleDateFormat df=new SimpleDateFormat("YYYY-MM-dd");
        String formateDate=df.format(d);
        lblTime.setText(formateDate);
    }

    private void setTime() {
        java.util.Date t=new java.util.Date();
        SimpleDateFormat df=new SimpleDateFormat("HH:mm:ss");
        String formateDate=df.format(t);
        lblDate.setText(formateDate);
    }
}
